"""led_ticker — Python client for the LED-Ticker BLE device."""
from .client import (
    LedTicker,
    cancel_timer,
    clear_status,
    get_apikey,
    get_display,
    get_locations,
    get_mode,
    get_power,
    get_status,
    get_tickers,
    get_timezone,
    get_version,
    get_wifi,
    reload,
    reset,
    set_apikey,
    set_brightness,
    set_display,
    set_locations,
    set_mode,
    set_pin_enforce,
    set_power,
    set_scroll_speed,
    set_status,
    set_tickers,
    set_timer,
    set_timezone,
    set_wifi,
)
from .errors import (
    AuthError,
    DeviceNotFoundError,
    LedTickerError,
    ProtocolError,
    ValidationError,
)
from .protocol import Display, Status

__all__ = [
    "AuthError",
    "DeviceNotFoundError",
    "Display",
    "LedTicker",
    "LedTickerError",
    "ProtocolError",
    "Status",
    "ValidationError",
    # one-shot helpers
    "cancel_timer",
    "clear_status",
    "get_apikey",
    "get_display",
    "get_locations",
    "get_mode",
    "get_power",
    "get_status",
    "get_tickers",
    "get_timezone",
    "get_version",
    "get_wifi",
    "reload",
    "reset",
    "set_apikey",
    "set_brightness",
    "set_display",
    "set_locations",
    "set_mode",
    "set_pin_enforce",
    "set_power",
    "set_scroll_speed",
    "set_status",
    "set_tickers",
    "set_timer",
    "set_timezone",
    "set_wifi",
]
